# -*- coding: utf-8 -*-
"""Iris_classifcation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GVfMUd8fGVf7w2K9ipYoMrSXOrk0GbKM
"""


